
const actionTypes = {
    CURRENTUSER: 'CURRENTUSER',
    USERUID: 'USERUID',
    USERDATA: 'USERDATA',
    COMPLAINT: 'COMPLAINT',
    PENDING: 'PENDING',
    RESOLVED: 'RESOLVED',
    NOTIFY: 'NOTIFY',
    FEEDBACKS: 'FEEDBACKS',
    ALLCOMPLAINT: 'ALLCOMPLAINT'
}

export default actionTypes